version: "3"
services:
  web:
    image: fulton/pegasus
    ports:
      - 8000:8000
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs:v0.4.16
    user: ipfs
    command: [ "daemon", "--enable-pubsub-experiment" ]
    ports:
      - 5001:5001
      - 8080:8080