version: "3"
services:
  web:
    image: fulton/pegasus
    environment: 
      - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=512m
    ports:
      - 8000:8000
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs
    user: ipfs
    ports:
      - 5001:5001
      - 8080:8080