version: "2.1"
services:
  web:
    image: fulton/pegasus
    oom_kill_disable: true
    environment: 
      - JVM_OPTS=-Xmx512m -Xms256m -XX:MaxPermSize=1024m
    ports:
      - 8000:8000
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs
    user: ipfs
    ports:
      - 5001:5001
      - 8080:8080