version: "2.2"
services:
  web:
    image: fulton/pegasus
    environment: 
      - JVM_OPTS=-Xmx512m -Xms256m -XX:MaxPermSize=512m
    ports:
      - 8000:8000
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs
    user: ipfs
    mem_limit: 50m
    ports:
      - 5001:5001
      - 8080:8080
